site_name: Kahlan documentation
site_description: Unit/BDD PHP Test Framework for Freedom, Truth, and Justice
repo_name: 'GitHub'
repo_url: https://github.com/kahlan/kahlan
pages:
- ['index.md', 'Index']
- ['why-this-one.md', 'Why This One?']
- ['getting-started.md', 'Getting Started']
- ['overview.md', 'Overview']
- ['matchers.md', 'Matchers']
- ['allow.md', 'Stubbing & Monkey Patching']
- ['test-double.md', 'Test Double']
- ['reporters.md', 'Reporters']
- ['pro-tips.md', 'Pro Tips']
- ['config-file.md', 'Kahlan-config.php']
- ['integration.md', 'Integration with popular frameworks']
- ['faq.md', 'FAQ']
theme: readthedocs
include_search: true
