site_name: Kahlan documentation
site_description: Unit/BDD PHP Test Framework for Freedom, Truth, and Justice
repo_name: 'GitHub'
repo_url: https://github.com/kahlan/kahlan
pages:
  - 'Overview': 'index.md'
  - 'Getting Started': 'getting-started.md'
  - 'DSL': 'dsl.md'
  - 'Matchers': 'matchers.md'
  - 'Method Stubbing & Monkey Patching': 'allow.md'
  - 'Test Double': 'test-double.md'
  - 'Quit Statement Patching': 'quit.md'
  - 'CLI Options': 'cli-options.md'
  - 'Reporters': 'reporters.md'
  - 'Pro Tips': 'pro-tips.md'
  - 'Kahlan-config.php': 'config-file.md'
  - 'Integration with popular frameworks': 'integration.md'
theme: readthedocs
